info:
  build:
    name: "@project.name@"
    description: "@project.description@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"

server:
  port: 9002
  tomcat:
    basedir: ./dptms-logs/${spring.application.name}/tomcat
    accesslog:
      enabled: true
      directory: ./access
      buffered: false
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i'
      prefix: ${spring.application.name}
      rotate: true
      suffix: .log

logging:
  config: classpath:config/local/logback.xml
#监控配置
management:
  health:
    # 关闭redis检测
    redis:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
