# 数据源配置
spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: ENC(l1mj+5jUSUC19Gvjx9XHklsb3sVj5/2uErYeoS0hHIdwbd1beKYLRubuIEaLVI0rmgAqh6C8LIBo5RfHvccb9CDnv8gWXB1Ode5y+i1BsrlOTDYWGX4g0VC06sWNViWOuURh9Peu6GPvfdc0UjJD9bKWG1yD7HCh)
      username: ENC(re1OBMgMM1C66IVlx1Yl2A==)
      password: ENC(9JegD8nwC6GISP1bsSMkfGoo6Yc3j9ZT)
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #      aop-patterns: com.ky.zstu.service.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,*.svg'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
  #Json时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 无视redis警告
  data:
    redis:
      repositories:
        enabled: false
  #redis配置
  redis:
    #数据库索引
    database: 1
    host: ENC(Ttic6Zj4SppdNUGyyN1bLRPCYd7FxO2M)
    port: ENC(RS1fm3OiI97A1gzz3jBBdw==)
    password: ENC(1XUbqRThqaIzV/joSjHX/GJtQ+lWeqYlSTXtgnVHlfiE9OLASPIh+w==)
    #连接超时时间
    timeout: 5000
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000

# mybatis配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.darren1112.dptms.common.spi
