zuul:
  routes:
    auth:
      path: /auth/**
      stripPrefix: false
      serviceId: dptms-auth
      sensitiveHeaders: "*"
    system-manage:
      path: /system-manage/**
      stripPrefix: false
      serviceId: dptms-system-manage
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

dptms:
  doc:
    gateway:
      enable: true
      resources: ${zuul.routes.auth.serviceId}, ${zuul.routes.system-manage.serviceId}
