dptms:
  auth:
    accessTokenExpiredSeconds: 86400
    refreshTokenExpiredSeconds: 604800
    clients:
      - client: dptms
        secret: 123456
        grantType: password,authorization_code,refresh_token
        scope: all
  doc:
    enable: true
    title: 认证中心接口文档
    description: 认证相关结果
    name: MrDarren
    email: ludaye1112@163.com
    version: "@project.version@"
